name: Matlab Docker image

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch: {}

jobs:

  test:
    runs-on: ubuntu-latest
    container: mathworks/matlab
    steps:
      - name: Run
        run: |
          echo "Hello world"

