name: Matlab Docker image

on:
  push:
    branches:
      - '**'
  pull_request:
  # workflow_dispatch: {}

jobs:

  test:
    runs-on: ubuntu-latest
    container: ghcr.io/giordano/julia-macos-test:mg-matlab
    steps:
      - name: Run
        run: |
          echo "Hello world"

